### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by ulthiel** [niklasf/chess-openings#28]
Could you specify the source of the opening names? They are different (but better because more detailed and logical!) from what I usually find in ECO databases.

**Comment by niklasf** [comment]
Most of the opening names were extracted from an ealier version of Lichess's opening database. I don't know which source Lichess was using, but I assume it was a product of manual research and other open source databases (maybe SCID?).

From there it was again manual work to clean the data and make sure naming is consistent, checking with internet searches for the opening name if in doubt. Still more inconsistencies were found and fixed by contributors later.

The data set was originally just names for positions. Matching moves were searched in a database of master games, to find the most common way to reach the opening positions. Where no matching games could be found, I searched the internet manually for the name. To make it easier, I built some ad-hoc utilities to accept pasted lines in the formats used by Wikipedia, 365chess.com, chess.com, etc. They are in Git history, but now useless.

**Comment by ulthiel** [comment]
Thanks for clarifying!

**Comment by Dboingue** [comment]
The question is great.  The answer is honest, But the issue should be left open as the answer seems to show something ubiquitous about many chess databases (this is no moral judgment, just my mathematical thirsty mind for reproducible data manipulations).

Also, it may give a chance to explain to me, what are the boundaries of the concept of "open data" when in context of open source code, AND chess data....   I would have hope to bi-direction input-ouput reproducibility at all the steps from source to release, to be included.  That may be my hope, but it may not be the reality... Nevertheless, this issue should be kept open in spite of the transparency of process given.

It clarifies the obligatory state of things, and the past, yes. But does not provide for the sources, or ability to reproduce from them.  it that is not open data concern. how should we call that (in science it would be considered part of the reproducible constraints, often independenly of the experimental design, so that the results could be reproduced with different design, in case the design created some artifacts for example, not saying this is here, just explaining the missing concept i percieve, in open data , if lichess is considering this to be open data. Then i would seek for other standards of public sharing.

I do not blame anything... just seeking full clarity on things...   we can strive to be open "things", does not mean it had to be perfect, but asknowledge the gaps toward the goal, might be even more in the spirit of trying to reach the goal.

**Comment by ulthiel** [comment]
Even though this would be great, you can't really demand this from a 1-person spare time project for the community on something as non-systematic as chess history. But maybe, one day, one could add "Alternative names" and "Reference" columns in the database to collect such information...
